# Generated by Django 5.2.3 on 2025-06-19 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userlibraryaccess",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userverification",
            name="last_resend_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userlibraryaccess",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
