# Generated by Django 5.2.3 on 2025-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_verified_userlibraryaccess_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverification",
            name="code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="userverification",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email Verification"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("ACCOUNT_ACTIVATION", "Account Activation"),
                    ("PHONE", "Phone Verification"),
                    ("OTP", "One-Time Password"),
                ],
                max_length=20,
            ),
        ),
    ]
