# Generated by Django 5.2.3 on 2025-06-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userverification_code_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_role_2798cb_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_is_acti_b7b5de_idx",
        ),
        migrations.RemoveField(
            model_name="adminprofile",
            name="can_approve_users",
        ),
        migrations.RemoveField(
            model_name="user",
            name="approval_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_approved",
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_verified"], name="accounts_us_role_120ec7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_verified"],
                name="accounts_us_is_acti_0584df_idx",
            ),
        ),
    ]
