# Generated by Django 5.2.3 on 2025-06-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_05b4bc_idx",
            old_name="notificatio_user_id_e19395_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_427e4b_idx",
            old_name="notificatio_user_id_a7d4c9_idx",
        ),
    ]
